[preview]
crop_mode=1
play_fps_limit=23.976
play_fps_limit_mode=0
prewiew_dialog_geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x4\xb8\0\0\0\x9c\0\0\t\xf7\0\0\x4\xb1\0\0\x4\xb8\0\0\0\xbb\0\0\t\xf7\0\0\x4\xb1\0\0\0\0\0\0\0\0\rp\0\0\x4\xb8\0\0\0\xbb\0\0\t\xf7\0\0\x4\xb1)
last_preview_frame=0
last_preview_scrollbar_position_x=0
last_preview_scrollbar_position_y=0
last_preview_timestamp=0
preview_dialog_maximized=true
zoom_mode=2